services:
  postgres:
    image: postgres:17
    container_name: postgres_db_todo
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_list
    ports:
      - "5433:5432"
    volumes:
      - todo_data_lps1402252051:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d todo_list"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: todo_list
      NODE_ENV: production

volumes:
  todo_data_lps1402252051: